/*
 * Copyright (c) 2014. Permission to use, copy, modify, distribute and sell this software and its documentation for any purpose is not granted without permission from owner, for more information please contact informeapplications@gmail.com
 */

package ca.informeapps.informeryerson.CampusLife.Directory;

public class DirectorySpinnerItems {

    private String[] spinnerItemValues = {"ABORIGINAL INITIATIVES", "ABORIGINAL SERVICES", "ACADEMIC COMPUTING",
            "ACADEMIC INTEGRITY", "ACCESS CENTRE", "ACCOUNTING AND FINANCE, TED ROGERS SCHOOL OF", "ADMISSIONS/RECRUIT",
            "AEROSPACE ENG.", "AIDS EDUCATION", "ALUMNI ADDRESS", "ALUMNI ENQUIRIES", "APPLIED RESEARCH & COMMERCIALIZATION",
            "ARCHITECTURE", "ARCHIVES", "ARTS & CONTEMPORARY", "ARTS UNDECLARED", "ATHLETICS", "AUDIO VISUAL", "BOARD SECRETARIAT",
            "BOOKSTORE", "BUSINESS MGMT.", "BUSINESS SYSTEMS", "C.U.P.E.", "CAREER CENTRE", "CASH OFFICE", "CCS", "CENTRE FOR URBAN ENERGY",
            "CERIS", "CESAR", "CHANCELLORS OFFICE", "CHEM. & BIOLOGY", "CHEMICAL ENG.", "CHILD & YOUTH CARE", "CIVIL ENG.", "CJRT", "CLMR",
            "CO-OP EDUCATION", "COMMUNICATIONS, GOVERNMENT AND COMMUNITY ENGAGEMENT", "COMMUNITY SERVICES", "COMPUTER SCIENCE",
            "CONFERENCE SERVICES", "CONTINUING ED.", "CONVOCATION", "COUNSELLING", "CPF", "CPRE", "CREATIVE INDUSTRIES", "CREDIT UNION",
            "CRIMINAL JUSTICE", "CSCA", "CURRICULUM MGT", "CVSS", "DISABILITY STUDIES", "DISCRIM & HARASSMENT", "DIVERSITY INSTITUTE",
            "DMPO", "DMZ", "DUPLICATING & PRINTING", "ECONOMICS", "ECS", "EDI", "ELECTRICAL ENG.", "ENGLISH", "ENGLISH SUPPORT", "ESSF",
            "EXPERIENTIAL LEARNING", "EYEOPENER", "FACILITIES RENTAL", "FACULTY OF ARTS", "FASHION", "FCAD",
            "FCAD, OPERATIONS & TECHNOLOGY SERVICES", "FEAS", "FINANCIAL SERVICES", "FOOD SERVICES", "FOS",
            "FYCEO", "FYCSO", "GCM", "GEOGRAPHY", "GERRARD RESOURCE", "GRADUATE STUDIES", "HEALTH PROMOTION",
            "HEALTH SERVICES", "HISTORY", "HOSPITALITY", "HOUSING", "HUMAN RESOURCES", "IMAGE ARTS", "IMAGE CENTRE",
            "IMDC", "INFO. SYST. SECURITY", "INTEGRATED RISK MGMT", "INTERIOR DESIGN", "INTERNAL AUDIT", "ISS",
            "ISTC / S.C.P.", "ITM", "JOURNALISM", "LANGUAGES, LITERATURES AND CULTURES", "LAW PRACTICE PROGRAM",
            "LEARNING SUCCESS", "LIBRARY", "LTO", "MAIL ROOM", "MATH CENTRE", "MATHEMATICS", "MECHANICAL ENG.",
            "MEDIA CENTRE", "MEDICAL CENTRE", "MIDWIFERY", "MLC", "MSWG", "NURSE PRACTITIONER", "NURSING",
            "NUTRITION", "OMBUDS OFFICE", "ONECARD", "OPERATIONS SUPPORT", "OPSEU", "OSAP", "P.T. EQUIPMENT",
            "P.T. ROOM BOOKING", "PARKING", "PHILOSOPHY", "PHOTOCOPY", "PHYSICS", "POLITICS", "PRESIDENTS OFFICE",
            "PROFESSIONAL COMM.", "PROFESSOR EMERITUS", "PROVOST & VP ACADEMIC", "PSYCHOLOGY", "PUBLIC AFFAIRS",
            "PURCHASING", "R&D", "RCG INSIGHT", "RECEIVING", "REGISTRARS OFFICE", "RESEARCH COMMUNICATIONS", "RESEARCH ETHICS",
            "RESEARCH GRANTS", "RESEARCH PARTNERSHIP DEVELOPMENT", "RESEARCH PLANNING, FINANCE AND EVALUATION", "RESS",
            "RETAIL MANAGEMENT", "RFA", "RSU", "RTA", "RYERSON CENTRE", "RYERSON INTERNATIONAL", "RYERSON THEATRE",
            "RYERSONIAN", "SCC", "SECURITY SERVICES", "SENATE", "SLP", "SOCIAL WORK", "SOCIOLOGY", "SOPHE", "SPANISH",
            "SPANNING GAPS", "SS, TRSM", "STUDENT AFFAIRS", "STUDENT DESK", "STUDENT FINANCIAL", "STUDENT LEARNING",
            "STUDENT RECORDS", "THEATRE SCHOOL", "TRI-MENTORING", "TRSM", "UBS", "UNIV. ADVANCEMENT", "UNIV. SCHEDULING",
            "UNIVERSITY  PLANNING", "URBAN PLANNING", "VICE PROVOST, ACADEMIC", "VICE PROVOST, FACULTY AFFAIRS",
            "VICE PROVOST, STUDENTS", "VIDEO POST", "VP ADMIN & FINANCE", "VP UNIV. ADVANCEMENT", "VPRI", "WRITING CENTRE"};
    private String[] spinnerItems = {"ABORIGINAL INITIATIVES", "ABORIGINAL SERVICES", "ACADEMIC COMPUTING", "ACADEMIC INTEGRITY",
            "ACCESS CENTRE", "ACCOUNTING AND FINANCE...", "ADMISSIONS/RECRUIT", "AEROSPACE ENG.", "AIDS EDUCATION", "ALUMNI ADDRESS",
            "ALUMNI ENQUIRIES", "APPLIED RESEARCH & COM...", "ARCHITECTURE", "ARCHIVES", "ARTS & CONTEMPORARY", "ARTS UNDECLARED",
            "ATHLETICS", "AUDIO VISUAL", "BOARD SECRETARIAT", "BOOKSTORE", "BUSINESS MGMT.", "BUSINESS SYSTEMS", "C.U.P.E.",
            "CAREER CENTRE", "CASH OFFICE", "CCS", "CENTRE FOR URBAN ENERGY", "CERIS", "CESAR", "CHANCELLORS OFFICE",
            "CHEM. & BIOLOGY", "CHEMICAL ENG.", "CHILD & YOUTH CARE", "CIVIL ENG.", "CJRT", "CLMR", "CO-OP EDUCATION",
            "COMMUNICATIONS, GOVERN...", "COMMUNITY SERVICES", "COMPUTER SCIENCE", "CONFERENCE SERVICES", "CONTINUING ED.",
            "CONVOCATION", "COUNSELLING", "CPF", "CPRE", "CREATIVE INDUSTRIES", "CREDIT UNION", "CRIMINAL JUSTICE", "CSCA",
            "CURRICULUM MGT", "CVSS", "DISABILITY STUDIES", "DISCRIM & HARASSMENT", "DIVERSITY INSTITUTE", "DMPO", "DMZ",
            "DUPLICATING & PRINTING", "ECONOMICS", "ECS", "EDI", "ELECTRICAL ENG.", "ENGLISH", "ENGLISH SUPPORT", "ESSF",
            "EXPERIENTIAL LEARNING", "EYEOPENER", "FACILITIES RENTAL", "FACULTY OF ARTS", "FASHION", "FCAD",
            "FCAD, OPERATIONS & TEC...", "FEAS", "FINANCIAL SERVICES", "FOOD SERVICES", "FOS", "FYCEO", "FYCSO",
            "GCM", "GEOGRAPHY", "GERRARD RESOURCE", "GRADUATE STUDIES", "HEALTH PROMOTION", "HEALTH SERVICES", "HISTORY",
            "HOSPITALITY", "HOUSING", "HUMAN RESOURCES", "IMAGE ARTS", "IMAGE CENTRE", "IMDC", "INFO. SYST. SECURITY",
            "INTEGRATED RISK MGMT", "INTERIOR DESIGN", "INTERNAL AUDIT", "ISS", "ISTC / S.C.P.", "ITM", "JOURNALISM",
            "LANGUAGES, LITERATURES...", "LAW PRACTICE PROGRAM", "LEARNING SUCCESS", "LIBRARY", "LTO", "MAIL ROOM", "MATH CENTRE",
            "MATHEMATICS", "MECHANICAL ENG.", "MEDIA CENTRE", "MEDICAL CENTRE", "MIDWIFERY", "MLC", "MSWG", "NURSE PRACTITIONER",
            "NURSING", "NUTRITION", "OMBUDS OFFICE", "ONECARD", "OPERATIONS SUPPORT", "OPSEU", "OSAP", "P.T. EQUIPMENT",
            "P.T. ROOM BOOKING", "PARKING", "PHILOSOPHY", "PHOTOCOPY", "PHYSICS", "POLITICS", "PRESIDENTS OFFICE", "PROFESSIONAL COMM.",
            "PROFESSOR EMERITUS", "PROVOST & VP ACADEMIC", "PSYCHOLOGY", "PUBLIC AFFAIRS", "PURCHASING", "R&D", "RCG INSIGHT", "RECEIVING",
            "REGISTRARS OFFICE", "RESEARCH COMMUNICATIONS", "RESEARCH ETHICS", "RESEARCH GRANTS", "RESEARCH PARTNERSHIP D...",
            "RESEARCH PLANNING, FIN...", "RESS", "RETAIL MANAGEMENT", "RFA", "RSU", "RTA", "RYERSON CENTRE", "RYERSON INTERNATIONAL",
            "RYERSON THEATRE", "RYERSONIAN", "SCC", "SECURITY SERVICES", "SENATE", "SLP", "SOCIAL WORK", "SOCIOLOGY", "SOPHE",
            "SPANISH", "SPANNING GAPS", "SS, TRSM", "STUDENT AFFAIRS", "STUDENT DESK", "STUDENT FINANCIAL", "STUDENT LEARNING",
            "STUDENT RECORDS", "THEATRE SCHOOL", "TRI-MENTORING", "TRSM", "UBS", "UNIV. ADVANCEMENT", "UNIV. SCHEDULING",
            "UNIVERSITY PLANNING", "URBAN PLANNING", "VICE PROVOST, ACADEMIC", "VICE PROVOST, FACULTY ...", "VICE PROVOST, STUDENTS",
            "VIDEO POST", "VP ADMIN & FINANCE", "VP UNIV. ADVANCEMENT", "VPRI", "WRITING CENTRE"};

    public String[] getSpinnerItemValues() {
        return spinnerItemValues;
    }

    public String[] getSpinnerItems() {
        return spinnerItems;
    }
}
